import { Profile, Role, PerformanceEvaluation, CommitteeKey, EventItem, Application, QuestionCategory } from '../types';

/**
 * ALIENS SPACE — RBAC & SECURITY MATRIX POLICY
 * 
 * Hierarchy:
 * OG > Team Head == Team Sub Head > Head == Sub Head (Full Head equivalence) > IR Evaluator > Member > Guest
 * 
 * Strict IR Rules:
 * 1. IR Member can ONLY evaluate active members strictly assigned to them (targetMember.assigned_ir === evaluator.id).
 * 2. IR Member CANNOT distribute/assign members (Distribution is strictly reserved for IR Head / Sub-Head / OG / Team Leadership).
 * 3. IR Member cannot manage questions outside IR or manage events/codes.
 * 4. Dual-Approval: Applications require approval from BOTH IR and Committee Head (or Sub Head).
 * 5. OG has Full System Override on all entities.
 * 6. Guest accounts (users without access codes) have read-only public access and CANNOT view member directories.
 * 7. Story cards can ONLY be generated by the member themselves.
 */

export function isOG(role: Role): boolean {
  return role === 'og';
}

export function isTeamLeadership(role: Role): boolean {
  return ['team_head', 'team_sub_head', 'og'].includes(role);
}

export function isLeaderOrHead(role: Role): boolean {
  return ['head', 'sub_head', 'team_head', 'team_sub_head', 'og'].includes(role);
}

/**
 * IR Leadership check: Strictly Head or Sub-Head of IR committee (or Team Leadership / OG).
 * An IR Member is NOT IR Leadership!
 */
export function isIRLeadership(profile: Profile): boolean {
  if (isTeamLeadership(profile.role)) return true;
  const isHeadTier = profile.role === 'head' || profile.role === 'sub_head';
  const isIRComm = (profile.committee || '').toLowerCase() === 'ir' || (profile.committee_key || '').toLowerCase() === 'ir';
  return isHeadTier && isIRComm;
}

/**
 * Checks if user is an IR evaluator (either IR Leadership or assigned IR Member)
 */
export function isIREvaluator(profile: Profile): boolean {
  if (isIRLeadership(profile)) return true;
  return profile.role === 'ir' || (profile.committee || '').toLowerCase() === 'ir';
}

/**
 * Determines if user can assign members to an IR evaluator
 * STRICT RULE: Only IR Head / Sub-Head or OG / Team Leadership can distribute members.
 */
export function canAssignIRMembers(actor: Profile): boolean {
  return isTeamLeadership(actor.role) || isIRLeadership(actor);
}

/**
 * Checks whether an evaluator is authorized to evaluate a specific target member.
 * STRICT RULE: IR Member can ONLY evaluate members where targetMember.assigned_ir === evaluator.id.
 * Sub-Head of a committee has FULL evaluation authority over their committee members.
 */
export function canEvaluateMember(evaluator: Profile, targetMember: Profile): { allowed: boolean; reason?: string } {
  if (evaluator.id === targetMember.id) {
    return { allowed: false, reason: 'لا يمكن تقييم نفسك' };
  }

  if (targetMember.membership_status !== 'active_member') {
    return { allowed: false, reason: 'المستخدم ليس عضواً نشطاً في التيم' };
  }

  // 1. OG / Team Leadership (can evaluate anyone except self)
  if (isTeamLeadership(evaluator.role)) {
    return { allowed: true };
  }

  // 2. IR Leadership (Head / Sub-Head of IR can evaluate all active members or board)
  if (isIRLeadership(evaluator)) {
    return { allowed: true };
  }

  // 3. Normal IR Member Evaluator — STRICT ENFORCEMENT: ONLY ASSIGNED MEMBERS!
  const isIRMember = evaluator.role === 'ir' || (evaluator.committee || '').toLowerCase() === 'ir';
  if (isIRMember) {
    if (targetMember.assigned_ir === evaluator.id || targetMember.assigned_ir === evaluator.full_name) {
      return { allowed: true };
    }
    return { 
      allowed: false, 
      reason: 'عضو الـ IR مصرح له حصرياً بتقييم الأعضاء المكلف بهم فقط (المسندين إليه). هذا العضو غير مسند إليك، وتوزيع الأعضاء مقتصر على رئيس لجنة الـ IR.' 
    };
  }

  // 4. Committee Head / Sub Head (Own Committee ONLY - Full Head Permissions for Sub-Head)
  const isCommitteeLeadership = evaluator.role === 'head' || evaluator.role === 'sub_head';
  if (isCommitteeLeadership) {
    const evaluatorComm = (evaluator.committee || evaluator.committee_key || '').toLowerCase();
    const targetComm = (targetMember.committee || targetMember.committee_key || '').toLowerCase();

    if (!evaluatorComm || evaluatorComm !== targetComm) {
      return {
        allowed: false,
        reason: `غير مصرح. رئيس/نائب لجنة ${evaluatorComm.toUpperCase()} يمكنه تقييم أعضاء لجنته فقط.`
      };
    }

    if (isTeamLeadership(targetMember.role)) {
      return { allowed: false, reason: 'لا يمكن تقييم قيادة التيم العليا' };
    }

    return { allowed: true };
  }

  return { allowed: false, reason: 'ليس لديك صلاحية تقييم الأعضاء' };
}

/**
 * Visibility rule for member evaluation history:
 * Visible ONLY to:
 * 1. The Member himself
 * 2. Assigned IR Evaluator
 * 3. Own Committee Head / Sub Head
 * 4. Team Head / Team Sub Head / OG
 */
export function canViewMemberEvaluations(viewer: Profile | null, targetMember: Profile): boolean {
  if (!viewer) return false;
  if (viewer.id === targetMember.id) return true;
  if (isTeamLeadership(viewer.role)) return true;

  if (targetMember.assigned_ir && (targetMember.assigned_ir === viewer.id || targetMember.assigned_ir === viewer.full_name)) return true;
  if (isIRLeadership(viewer) && (targetMember.is_board_member || targetMember.assigned_ir === viewer.id)) return true;

  const isCommLeader = viewer.role === 'head' || viewer.role === 'sub_head';
  if (isCommLeader) {
    const viewerComm = (viewer.committee || viewer.committee_key || '').toLowerCase();
    const targetComm = (targetMember.committee || targetMember.committee_key || '').toLowerCase();
    if (viewerComm && viewerComm === targetComm) {
      return true;
    }
  }

  return false;
}

/**
 * Returns strictly the list of members the evaluator is allowed to evaluate
 */
export function getEvaluatableMembers(evaluator: Profile, allMembers: Profile[]): Profile[] {
  return allMembers.filter(m => canEvaluateMember(evaluator, m).allowed);
}

/**
 * Strict Privacy & Confidentiality Rule for Member Phone Numbers & WhatsApp:
 * A member's phone number / WhatsApp link MUST ONLY be visible to:
 * 1. The member themselves (viewing own profile)
 * 2. The specific Assigned IR Evaluator (targetMember.assigned_ir === actor.id or actor.full_name)
 * 3. High Board / Team Leadership (role === 'og', 'team_head', 'team_sub_head' or is_board_member === true)
 * 4. IR Leadership (Head / Sub-Head of IR committee)
 * 
 * For all others (ordinary members, other committees, public): Phone numbers & WhatsApp contacts are strictly hidden/masked for confidentiality.
 */
export function canViewMemberPhone(actor: Profile | null, targetMember: Profile): boolean {
  if (!actor || !targetMember.phone) return false;
  // 1. Self
  if (actor.id === targetMember.id) return true;
  // 2. High Board / Team Leadership / OG
  if (isTeamLeadership(actor.role) || actor.is_board_member) return true;
  // 3. IR Leadership (Head / Sub-Head of IR)
  if (isIRLeadership(actor)) return true;
  // 4. Assigned IR Evaluator strictly assigned to this member
  if (targetMember.assigned_ir && (targetMember.assigned_ir === actor.id || targetMember.assigned_ir === actor.full_name)) {
    return true;
  }
  return false;
}

/**
 * Checks if user has permission to open direct WhatsApp conversation with a member
 * Strictly requires canViewMemberPhone permission!
 */
export function canContactMemberWhatsApp(actor: Profile | null, targetMember: Profile): boolean {
  return canViewMemberPhone(actor, targetMember);
}

/**
 * Checks if user can access the Member Directory and search for members
 * STRICT RULE: Guests (unauthenticated or role === 'guest') CANNOT access the directory.
 */
export function canAccessMemberDirectory(actor: Profile | null): boolean {
  if (!actor) return false;
  if (actor.role === 'guest' || actor.membership_status === 'guest') return false;
  return true;
}

/**
 * Strict Rule for Story Card Generation:
 * An active member can ONLY generate and share their OWN story card.
 * Nobody is allowed to generate another member's story card!
 */
export function canGenerateStoryCard(actor: Profile | null, targetMember: Profile): boolean {
  if (!actor) return false;
  return actor.id === targetMember.id;
}

/**
 * Checks if user can manage events for a specific committee scope
 * Sub-Head has full management rights alongside Head
 */
export function canManageEvent(actor: Profile, event?: EventItem): boolean {
  if (isTeamLeadership(actor.role)) return true;
  
  const isCommLeader = actor.role === 'head' || actor.role === 'sub_head';
  if (!isCommLeader) return false;

  if (!event) return true; // Can create event for own committee

  const actorComm = (actor.committee || actor.committee_key || '').toLowerCase();
  const eventComm = (event.committee_key || '').toLowerCase();

  // Can manage if event belongs to own committee or was created by actor
  if (event.created_by_id === actor.id) return true;
  if (eventComm === actorComm) return true;

  return false;
}

/**
 * Checks if user can review & approve/reject an applicant
 * Sub-Head has identical review and approval authority to Head
 */
export function canReviewApplication(
  actor: Profile, 
  application: Application
): { canDecideAsIR: boolean; canDecideAsHead: boolean; canOverrideAsOG: boolean } {
  const isOGUser = actor.role === 'og';
  const isTeamLead = isTeamLeadership(actor.role);
  const isIR = isIREvaluator(actor) || isIRLeadership(actor);

  const actorComm = (actor.committee || actor.committee_key || '').toLowerCase();
  const appComm = (application.committee_key || '').toLowerCase();
  const isCommLeader = (actor.role === 'head' || actor.role === 'sub_head') && actorComm === appComm;

  return {
    canDecideAsIR: isIR || isTeamLead || isOGUser,
    canDecideAsHead: isCommLeader || isTeamLead || isOGUser,
    canOverrideAsOG: isOGUser || isTeamLead
  };
}

/**
 * Checks if user can manage recruitment questions in a given category
 * Sub-Head has identical question management rights
 */
export function canManageQuestions(
  actor: Profile, 
  category: QuestionCategory, 
  targetCommitteeKey?: CommitteeKey
): boolean {
  if (isTeamLeadership(actor.role)) return true;

  if (category === 'global') {
    return isTeamLeadership(actor.role);
  }

  if (category === 'ir') {
    return isIRLeadership(actor) || (actor.role === 'ir' && actor.is_board_member);
  }

  if (category === 'committee' && targetCommitteeKey) {
    const isCommLeader = actor.role === 'head' || actor.role === 'sub_head';
    const actorComm = (actor.committee || actor.committee_key || '').toLowerCase();
    return isCommLeader && actorComm === targetCommitteeKey.toLowerCase();
  }

  return false;
}

/**
 * Checks if user has permission to access the Data Analytics & Export Hub
 */
export function canAccessDataAnalytics(actor: Profile | null): boolean {
  if (!actor) return false;
  if (isTeamLeadership(actor.role)) return true;
  if (isIRLeadership(actor)) return true;
  if (actor.role === 'head' || actor.role === 'sub_head') return true;
  
  // Data analysis / Secretary specialists
  const comm = (actor.committee || actor.committee_key || '').toLowerCase();
  const pos = (actor.position || '').toLowerCase();
  if (comm === 'secretary' || pos.includes('data') || pos.includes('analyst')) return true;

  return false;
}

/**
 * Checks if user can access recruitment review tab
 */
export function canAccessRecruitmentReview(actor: Profile | null): boolean {
  if (!actor) return false;
  return isIREvaluator(actor) || isIRLeadership(actor) || actor.role === 'head' || actor.role === 'sub_head' || isTeamLeadership(actor.role);
}

/**
 * Checks if user can manage live CMS / site content settings
 */
export function canAccessOGCMS(actor: Profile | null): boolean {
  if (!actor) return false;
  return isOG(actor.role) || isTeamLeadership(actor.role);
}

/**
 * Checks if user can comment on gallery photos
 */
export function canCommentOnGallery(actor: Profile | null): boolean {
  if (!actor) return false;
  return true;
}
